correct_mm_edges = [r'e \d+ \d+ .*_requ .*_Requ .*_Connector',
                    r'e \d+ \d+ .*_requ .*_Connector .*_Requ',
                    r'e \d+ \d+ .*_requ .*_Requ .*_Component', 
                    r'e \d+ \d+ .*_requ .*_Component .*_Requ',
                    r'e \d+ \d+ .*_requ .*_Package .*_Requ', 
                    r'e \d+ \d+ .*_src .*_Connector .*_Port',  
                    r'e \d+ \d+ .*_con .*_Package .*_Connector',  
                    r'e \d+ \d+ .*_t .*_Connector .*_Port', 
                    r'e \d+ \d+ .*_package .*_Package .*_Package', 
                    r'e \d+ \d+ .*_port .*_Component .*_Port', 
                    r'e \d+ \d+ .*_port .*_Port .*_Component',
                    r'e \d+ \d+ .*_im .*_Package .*_Im',  
                    r'e \d+ \d+ .*_im .*_Component .*_Im', 
                    r'e \d+ \d+ .*_component .*_Im .*_Component', 
                    r'e \d+ \d+ .*_component .*_Package .*_Component']